djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tfp/', include('trafficflowprediction.urls', namespace='trafficflowprediction')),
]

trafficflowprediction/urls.py
from django.urls import path

from trafficflowprediction.views import Upload, show, Update, Delete, Detail, Clean, Prediction, other, index

app_name = 'trafficflowprediction'

urlpatterns = [
    path('', index, name='index'),
    path('upload/', Upload.as_view(), name='upload'),
    path('show/<int:p>/', show, name='show'),
    path('<int:pk>/detail/', Detail.as_view(), name='detail'),
    path('<int:pk>/update/', Update.as_view(), name='update'),
    path('<int:pk>/delete/', Delete.as_view(), name='delete'),
    path('clean/', Clean.as_view(), name='clean'),
    path('prediction/', Prediction.as_view(), name='prediction'),
    path('other/', other, name='other'),
]

trafficflowprediction/models.py
from django.db import models


# Create your models here.
class CarInfo(models.Model):
    lane_name = models.CharField(max_length=15)
    lane_code = models.CharField(max_length=7)
    time = models.CharField(max_length=22)
    car_type = models.CharField(max_length=3)
    speed = models.PositiveSmallIntegerField()
    car_length = models.PositiveSmallIntegerField()
    axles = models.PositiveSmallIntegerField()
    total_weight = models.PositiveSmallIntegerField()
    axle1_weight = models.PositiveSmallIntegerField()
    axle2_weight = models.PositiveSmallIntegerField()
    axle3_weight = models.PositiveSmallIntegerField()
    axle4_weight = models.PositiveSmallIntegerField()
    axle5_weight = models.PositiveSmallIntegerField()
    axle6_weight = models.PositiveSmallIntegerField()
    axle7_weight = models.PositiveSmallIntegerField()
    axle8_weight = models.PositiveSmallIntegerField()
    axle9_weight = models.PositiveSmallIntegerField()
    axle10_weight = models.PositiveSmallIntegerField()
    overload = models.CharField(max_length=5)
    overspeed = models.CharField(max_length=5)
    state = models.CharField(max_length=5)

    class Meta:
        permissions = ()

trafficflowprediction/forms.py
from django import forms

from trafficflowprediction.models import CarInfo


class CarInfoForm(forms.ModelForm):
    # 配置中心，修改关于CSS的内容
    class Meta:
        model = CarInfo
        fields = '__all__'  # 验证所有字段

        widgets = {
            'lane_name': forms.TextInput(attrs={'class': 'form-control'}),
            'lane_code': forms.TextInput(attrs={'class': 'form-control'}),
            'time': forms.TextInput(attrs={'class': 'form-control'}),
            'car_type': forms.TextInput(attrs={'class': 'form-control'}),
            'speed': forms.NumberInput(attrs={'class': 'form-control'}),
            'car_length': forms.NumberInput(attrs={'class': 'form-control'}),
            'axles': forms.NumberInput(attrs={'class': 'form-control'}),
            'total_weight': forms.NumberInput(attrs={'class': 'form-control'}),
            'axle1_weight': forms.NumberInput(attrs={'class': 'form-control'}),
            'axle2_weight': forms.NumberInput(attrs={'class': 'form-control'}),
            'axle3_weight': forms.NumberInput(attrs={'class': 'form-control'}),
            'axle4_weight': forms.NumberInput(attrs={'class': 'form-control'}),
            'axle5_weight': forms.NumberInput(attrs={'class': 'form-control'}),
            'axle6_weight': forms.NumberInput(attrs={'class': 'form-control'}),
            'axle7_weight': forms.NumberInput(attrs={'class': 'form-control'}),
            'axle8_weight': forms.NumberInput(attrs={'class': 'form-control'}),
            'axle9_weight': forms.NumberInput(attrs={'class': 'form-control'}),
            'axle10_weight': forms.NumberInput(attrs={'class': 'form-control'}),
            'overload': forms.TextInput(attrs={'class': 'form-control'}),
            'overspeed': forms.TextInput(attrs={'class': 'form-control'}),
            'state': forms.TextInput(attrs={'class': 'form-control'}),
        }

        labels = {
            'lane_name': '车道名称',
            'lane_code': '车道代码',
            'time': '时间',
            'car_type': '车型',
            'speed': '速度',
            'car_length': '车长',
            'axles': '轴数',
            'total_weight': '总重',
            'axle1_weight': '轴重1',
            'axle2_weight': '轴重2',
            'axle3_weight': '轴重3',
            'axle4_weight': '轴重4',
            'axle5_weight': '轴重5',
            'axle6_weight': '轴重6',
            'axle7_weight': '轴重7',
            'axle8_weight': '轴重8',
            'axle9_weight': '轴重9',
            'axle10_weight': '轴重10',
            'overload': '超重',
            'overspeed': '超速',
            'state': '状态',
        }

trafficflowprediction/views.py
import json

import os
from pathlib import Path
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db import connection
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import DetailView, UpdateView, DeleteView
import pandas as pd

from trafficflowprediction import utils
from trafficflowprediction.forms import CarInfoForm
from trafficflowprediction.models import CarInfo


def other(request):
    return render(request, 'trafficflowprediction/other.html')


def index(request):
    return render(request, 'trafficflowprediction/base.html')


class Upload(View):
    current = 0

    def get(self, request):
        exist = request.GET.get('getProgressNum')
        if exist:
            # print(Upload.current)  # debug
            return HttpResponse(Upload.current)
        else:
            return render(request, 'trafficflowprediction/upload.html')

    def post(self, request):
        # 读取文件内容，保存数据库
        file = request.FILES.get('file_obj')
        response = {'status': 200, 'msg': None}
        data = pd.DataFrame(pd.read_excel(file))
        total = data.shape[0]
        data.fillna(0, inplace=True)
        for index2, row in data.iterrows():
            Upload.current = int(index2 / total * 100)
            # print(Upload.current)
            car = CarInfo(lane_name=row['车道名称'], lane_code=row['车道代码'], time=row['时间'],
                          car_type=row['车型'], speed=row['车速（km/h）'], car_length=row['车长（cm)'],
                          axles=row['轴数（根)'], total_weight=row['总重（kg）'], axle1_weight=row['轴重1（kg）'],
                          axle2_weight=row['轴重2（kg）'], axle3_weight=row['轴重3（kg）'], axle4_weight=row['轴重4（kg）'],
                          axle5_weight=row['轴重5（kg）'], axle6_weight=row['轴重6（kg）'], axle7_weight=row['轴重7（kg）'],
                          axle8_weight=row['轴重8（kg）'], axle9_weight=row['轴重9（kg）'], axle10_weight=row['轴重10（kg）'],
                          overload=row['超重'], overspeed=row['超速'], state=row['状态'])
            car.save()
        response['msg'] = "文件上传成功"
        return JsonResponse(response, safe=False)


class CustomerPaginator(Paginator):
    """
    继承Paginator类，用于保留原有功能、并扩展新的功能
    """

    def __init__(self, current_page, per_pager_num, *args, **kwargs):
        super(CustomerPaginator, self).__init__(*args, **kwargs)
        self.current_page = int(current_page)  # 当前页码
        self.per_page_num = int(per_pager_num)  # 分页自定制显示最多页码个数

    def pager_num_range(self):
        '''
        CustomerPaginator自定制新功能：显示分页页码
        :return:
        '''
        if self.num_pages < self.per_page_num:
            # 当数据的总页码数<自定制的每页显示分页页码数时，显示：1到总页码数
            return range(1, self.num_pages + 1)

        # 自定制每页显示页码数/2，取整，主要是想当前页码显示在页码中央：
        part = int(self.per_page_num / 2)

        if self.current_page <= part:
            # 如果当前页码小于自定制每页显示页码数的一半
            return range(1, self.per_page_num + 1)

        if self.current_page + part > self.num_pages:
            # 如果当前页码加上自定制每页显示页码数的一半,大于总页码数：
            return range(self.num_pages - self.per_page_num + 1, self.num_pages + 1)
        # 在上面的极端值情况后，常规情况是取当前页前后-+part范围
        return range(self.current_page - part, self.current_page + part + 1)


def show(request, p):
    stu_list = CarInfo.objects.all()

    current_page = int(p)
    # 由于上面使用CustomerPaginator继承了Paginator，所以这里使用CustomerPaginator实例化，
    # 传入4个参数：当前页码、每页显示页码个数、全部数据、每页显示数据条数
    paginator = CustomerPaginator(current_page, 10, stu_list, 14)

    try:
        # page对象
        posts = paginator.page(current_page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, "trafficflowprediction/show.html", {"posts": posts})


class Detail(DetailView):
    model = CarInfo
    template_name = 'trafficflowprediction/detail.html'


class Update(UpdateView):
    form_class = CarInfoForm
    model = CarInfo
    template_name = 'trafficflowprediction/update.html'
    success_url = reverse_lazy('trafficflowprediction:show', kwargs={'p': 1})


class Delete(DeleteView):
    model = CarInfo
    template_name = 'trafficflowprediction/delete.html'
    success_url = reverse_lazy('trafficflowprediction:show', kwargs={'p': 1})


class Clean(View):

    def my_custom_sql(self, sql):
        before = CarInfo.objects.all().count()
        with connection.cursor() as cursor:
            cursor.execute(sql)
            row = cursor.fetchone()
        after = CarInfo.objects.all().count()
        return before - after

    def get(self, request):
        return render(request, 'trafficflowprediction/clean.html')

    def post(self, request):
        # 1、获取前端用户提交的清洗数据规则
        # value = request.POST.get('car_length')
        # value2 = request.POST.get('speed')
        value3 = request.POST.get('axles')
        value4 = request.POST.get('car_type')
        value5 = request.POST.get('overload')
        value6 = request.POST.get('overspeed')
        value7 = request.POST.get('state')

        # 2、对数据库数据进行操作
        sql = 'DELETE FROM trafficflowprediction_carinfo WHERE car_length is null OR speed is null'

        if value3 == '考虑':
            sql = sql + " OR axles is null"
        if value4 != 'none':
            sql = sql + " OR car_type=='" + value4 + "'"
        if value5 != 'none':
            sql = sql + " OR overload=='" + value5 + "'"
        if value6 != 'none':
            sql = sql + " OR overspeed=='" + value6 + "'"
        if value7 != 'none':
            sql = sql + " OR state=='" + value7 + "'"

        # raw()处理的是select语句；update，delete，insert不能采取这种方式
        # res = CarInfo.objects.raw(sql)
        res = self.my_custom_sql(sql)
        # data = {'result': res}
        # 3、前端返回清洗成功提示
        return render(request, 'trafficflowprediction/success.html', {'result': json.dumps(res)})


class Prediction(View):

    def process_data(self, direction, minutes=5):
        """
        处理数据库数据，取数据库某一天的数据，进行预测
        :param minutes: 间隔
        :param direction: 上行或者下行
        :return:none
        """
        temp = '上'
        if direction == 'down':
            temp = '下'
        car_list = CarInfo.objects.all()
        l = []  # 存放时间这一列的数据
        for item in car_list:
            if item.lane_name[0] != temp:
                continue
            l.append(item.time)
        l.sort()

        time_sequence, cnts = [], []
        # 统计每5分钟的车辆数
        # 一天是288个5分钟
        # 得到该文件的第一天
        firstdate = str(l[0][0:l[0].find(' ')])
        intervals = []  # 时间区间，长度：288
        str2 = '{:0>2d}:{:0>2d}:00.0'
        for hour in range(24):
            for minute in range(0, 60, int(minutes)):
                intervals.append(str2.format(hour, minute))
        intervals.append(str2.format(24, 0))
        start = 0
        while start < len(l):
            for j in range(1, len(intervals)):
                cnt = 0
                for i in range(start, len(l)):
                    blankindex = l[i].find(' ')
                    if l[i][0:blankindex] != firstdate:
                        start = i
                        time_sequence.append(firstdate + ' ' + intervals[j - 1])
                        cnts.append(cnt)
                        break
                    if l[i][blankindex + 1:] < intervals[j]:
                        cnt += 1
                        if i + 1 == len(l):
                            start = i + 1
                            time_sequence.append(firstdate + ' ' + intervals[j - 1])
                            cnts.append(cnt)
                            break
                    else:
                        start = i
                        time_sequence.append(firstdate + ' ' + intervals[j - 1])
                        cnts.append(cnt)
                        break
            # 下一天
            if start < len(l):
                firstdate = l[start][0:l[start].find(' ')]

        dataframe = pd.DataFrame({minutes + ' Minutes': time_sequence, 'Flow': cnts})
        path = os.getcwd() + "\\trafficflowprediction\\data\\" + minutes + '_' + direction + ".csv"
        dataframe.to_csv(path, index=False)


    def get(self, request):
        return render(request, 'trafficflowprediction/prediction.html')

    def post(self, request):
        direction = request.POST.get('direction')
        internal = request.POST.get('internal')
        # 处理数据，将结果保存在/data/data_{{internal}}.csv文件
        self.process_data(direction, internal)
        # 根据direction和internal调用不同的模型
        p = utils.Prediction(direction, internal)
        loss = p.predicte()
        # 将预测得到的图片以及指标发送给前端
        pic = 'trafficflowprediction/img/' + internal + '_' + direction + '.png'
        return render(request, 'trafficflowprediction/prediction_show.html', {'img': pic, 'loss': loss})

trafficflowprediction/templates/trafficflowprediction/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {#  settings设置trafficflowprediction忘记在polls后加逗号，导致下面报“引用未知文件”错误  #}
    <link href="{% static 'trafficflowprediction/libs/bootstrap.css' %}" rel="stylesheet">
    <script type="text/javascript" src="{% static 'trafficflowprediction/libs/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'trafficflowprediction/libs/bootstrap.min.js' %}"></script>
    <title>{% block title_content %}主页{% endblock %}</title>
    {% block script_content %}{% endblock %}
</head>
<body>
<div class="container">
    <div class="row" style="height: 40vw;margin-top: 30px">
        <div class="col-md-2" style="background-color: skyblue ">
            <nav class="nav flex-column">
                <a class="nav-link active" aria-current="page" href="{% url 'trafficflowprediction:upload' %}">文件选择</a>
                <a class="nav-link" href="{% url 'trafficflowprediction:show' p=1%}">数据显示</a>
                <a class="nav-link" href="{% url 'trafficflowprediction:clean' %}">数据筛选</a>
                <a class="nav-link" href="{% url 'trafficflowprediction:prediction' %}">预测</a>
                <a class="nav-link" href="{% url 'trafficflowprediction:other' %}">其他</a>
            </nav>
        </div>
        <div class="col-md-10" style="background-color:lightskyblue">
            {% block data_content %}<h1 class="text-center">LSTM预测交通流展示</h1>{% endblock %}
        </div>
    </div>
</div>
</body>
</html>

trafficflowprediction/templates/trafficflowprediction/clean.html
{% extends 'trafficflowprediction/base.html' %}
{% block title_content %}数据清洗{% endblock %}

{% block data_content %}
    <form class="form-control" action="{% url  'trafficflowprediction:clean' %} " method="post">
        {% csrf_token %}
        <table class="table">
            <thead>
            <tr>
                <th>选项</th>
                <th>取值</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td><label>车长</label></td>
                <td><input type="checkbox" checked disabled></td>
            </tr>
            <tr>
                <td><label>车速</label></td>
                <td><input type="checkbox" checked disabled></td></td>
            </tr>
            <tr>
                <td><label>轴数</label></td>
                <td><select name="axles">
                    <option value="考虑">考虑</option>
                    <option selected value="不考虑">不考虑</option>
                </select></td>
            </tr>
            <tr>
                <td><label>车型</label></td>
                <td><select name="car_type">
                    <option selected value="none">不考虑</option>
                    <option value="小客车">小客车</option>
                    <option value="小货车">小货车</option>
                    <option value="中货车">中货车</option>
                    <option value="大货车">大货车</option>
                    <option value="大客车">大客车</option>
                </select></td>
            </tr>
            <tr>
                <td><label>超速</label></td>
                <td><select name="overspeed">
                    <option selected value="none">不考虑</option>
                    <option value="正常">正常</option>
                    <option value="超速">超速</option>
                </select></td>
            </tr>
            <tr>
                <td><label>超重</label></td>
                <td><select name="overload">
                    <option selected value="none">不考虑</option>
                    <option value="正常">正常</option>
                    <option value="超重">超重</option>
                </select></td>
            </tr>
            <tr>
                <td><label>状态</label></td>
                <td><select name="state">
                    <option selected value="none">不考虑</option>
                    <option value="正常">正常</option>
                    <option value="线圈出错">线圈出错</option>
                    <option value="车辆跨道行驶">车辆跨道行驶</option>
                </select></td>
            </tr>
            <tr>
                <td><button class="btn btn-primary" type="submit">清洗</button></td>
            </tr>
            </tbody>
        </table>
    </form>
{% endblock %}

trafficflowprediction/templates/trafficflowprediction/delete.html
{% extends 'trafficflowprediction/base.html' %}
{% block title_content %}删除数据{% endblock %}

{% block data_content %}
    <div class="col-4">
        <div class="alert alert-danger mb-4">是否删除此条记录？</div>
        <form action="{% url 'trafficflowprediction:delete' object.pk %}" method="post">
            {% csrf_token %}
            <button class="btn btn-danger" type="submit">删除</button>
        </form>
    </div>
{% endblock %}

trafficflowprediction/templates/trafficflowprediction/detail.html
{% extends 'trafficflowprediction/base.html' %}
{% block title_content %}数据详情{% endblock %}

{# 数据item详情 #}
{# 修改，删除 #}

{% block data_content %}
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">数据库主键为{{ object.pk }}的信息</h5>
            <p class="card-text">
                车道名称：<span class="badge badge-secondary bg-info">{{ object.lane_name }}</span>
            </p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">车道编码：{{ object.lane_code }}</li>
            <li class="list-group-item">时间：{{ object.time }}</li>
            <li class="list-group-item">车型：{{ object.car_type }}</li>
            <li class="list-group-item">车速：{{ object.speed }}</li>
            <li class="list-group-item">车长：{{ object.car_length }}</li>
            <li class="list-group-item">轴数：{{ object.axles }}</li>
            <li class="list-group-item">总重：{{ object.total_weight }}</li>
            <li class="list-group-item">超重：{{ object.overload }}</li>
            <li class="list-group-item">超速：{{ object.overspeed }}</li>
            <li class="list-group-item">状态：{{ object.state }}</li>
            <li class="list-group-item">轴重1：{{ object.axle1_weight }}</li>
            <li class="list-group-item">轴重2：{{ object.axle2_weight }}</li>
            <li class="list-group-item">轴重3：{{ object.axle3_weight }}</li>
            <li class="list-group-item">轴重4：{{ object.axle4_weight }}</li>
            <li class="list-group-item">轴重5：{{ object.axle5_weight }}</li>
            <li class="list-group-item">轴重6：{{ object.axle6_weight }}</li>
            <li class="list-group-item">轴重7：{{ object.axle7_weight }}</li>
            <li class="list-group-item">轴重8：{{ object.axle8_weight }}</li>
            <li class="list-group-item">轴重9：{{ object.axle9_weight }}</li>
            <li class="list-group-item">轴重10：{{ object.axle10_weight }}</li>
        </ul>
        <div class="card-body">
            <a href="{% url 'trafficflowprediction:update' object.pk %}" class="card-link">编辑</a>
            <a href="{% url 'trafficflowprediction:delete' object.pk %}" class="card-link">删除</a>
            <a class="float-end" href="{% url 'trafficflowprediction:show' p=1 %}">返回</a>
        </div>
    </div>
{% endblock %}

trafficflowprediction/templates/trafficflowprediction/other.html
{% extends 'trafficflowprediction/base.html' %}
{% block title_content %}其他{% endblock %}

{% block data_content %}
    </br>
    </br>
    </br>
    </br>
    </br>
    </br>
    </br>
    </br>
    </br>
    </br>
    <h1 class="text-center" style="font-family: SimSun;">一切有为法，如梦幻泡影。</h1>
    <h1 class="text-center" style="font-family: SimSun;">如露亦如电，应作如是观。</h1>
{% endblock %}

trafficflowprediction/templates/trafficflowprediction/prediction.html
{% extends 'trafficflowprediction/base.html' %}
{% block title_content %}预测{% endblock %}

{% block data_content %}
    <form class="form-control" method="post" action="{% url 'trafficflowprediction:prediction' %}">
        {% csrf_token %}
        <table class="table">
            <thead>
            <tr>
                <th>选项</th>
                <th>取值</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td><label>方向</label></td>
                <td><select name="direction">
                    <option value="down">下行</option>
                    <option selected value="up">上行</option>
                </select></td>
            </tr>
            <tr>
                <td><label>间隔</label></td>
                <td><select name="internal">
                    <option selected value="5">5分钟</option>
                    <option value="10">10分钟</option>
                </select></td>
            </tr>
            <tr>
                <td>
                    <button class="btn btn-primary" type="submit">预测</button>
                </td>
            </tr>
            </tbody>
        </table>
    </form>
{% endblock %}

trafficflowprediction/templates/trafficflowprediction/show.html
{% extends 'trafficflowprediction/base.html' %}
{% block title_content %}数据展示{% endblock %}

{# 显示数据，分页显示 #}
{% block data_content %}
    <table class="table table-bordered table-striped table-hover">
        <thead>
        <tr>
            <th>车道名称</th>
            <th>车道代码</th>
            <th>时间</th>
            <th>车型</th>
            <th>车速(km/h)</th>
            <th>车长(cm)</th>
            <th>轴数(根)</th>
            <th>总重(kg)</th>
            <th>超重</th>
            <th>超速</th>
            <th>状态</th>
        </tr>
        </thead>
        <tbody>
        {% for item in posts %}
            <tr>
                <td><a href="{% url 'trafficflowprediction:detail' item.pk %}">{{ item.lane_name }}</a></td>
                <td>{{ item.lane_code }}</td>
                <td>{{ item.time }}</td>
                <td>{{ item.car_type }}</td>
                <td>{{ item.speed }}</td>
                <td>{{ item.car_length }}</td>
                <td>{{ item.axles }}</td>
                <td>{{ item.total_weight }}</td>
                <td>{{ item.overload }}</td>
                <td>{{ item.overspeed }}</td>
                <td>{{ item.state }}</td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="11">
                    暂无数据
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <nav aria-label="Page navigation">
        <ul class="pagination" style="margin-top: 0px">
            <li class="page-item"><a class="page-link" href="{% url 'trafficflowprediction:show' p=1 %}" aria-label="F">
                <span aria-hidden="true">首页</span>
            </a></li>
            {% if posts.has_previous %}
                <li class="page-item"><a class="page-link"
                                         href="{% url 'trafficflowprediction:show' p=posts.previous_page_number %}"
                                         aria-label="Previous">
                    <span aria-hidden="true">上一页</span>
                </a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="#" aria-label="Previous">
                    <span aria-hidden="true">上一页</span></a>
                </li>
            {% endif %}
            {% for i in posts.paginator.pager_num_range %}
                {% if i == posts.number %}
                    <li class="page-item"><a class="page-link" style="background-color: #9acfea;"
                                             href="{% url 'trafficflowprediction:show' p=i %}">{{ i }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link"
                                             href="{% url 'trafficflowprediction:show' p=i %}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if posts.has_next %}
                <li class="page-item"><a class="page-link"
                                         href="{% url 'trafficflowprediction:show' p=posts.next_page_number %}"
                                         aria-label="Next">
                    <span aria-hidden="true">下一页</span>
                </a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="#" aria-label="Next">
                    <span aria-hidden="true">下一页</span>
                </a></li>
            {% endif %}
            <li class="page-item"><a class="page-link"
                                     href="{% url 'trafficflowprediction:show' p=posts.paginator.num_pages %}"
                                     aria-label="Last">
                <span aria-hidden="true">尾页</span>
            </a></li>
        </ul>
    </nav>
{% endblock %}

trafficflowprediction/templates/trafficflowprediction/update.html
{% extends 'trafficflowprediction/base.html' %}
{% block title_content %}更新数据{% endblock %}
{% load mytag %}

{% block data_content %}
    <form action="{% url 'trafficflowprediction:update' object.pk %}" method="post">
    {% csrf_token %}
    {% for item in form %}
      <div class="col-md-6 mb-3">
        {{ item|label_class:'form-label' }}
        {{ item }}
        {{ item.errors }}
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">保存</button>
    <a class="btn btn-danger" href="{% url 'trafficflowprediction:detail' object.pk %}">返回</a>
  </form>
{% endblock %}

trafficflowprediction/templates/trafficflowprediction/upload.html
{% extends 'trafficflowprediction/base.html' %}
{% load static %}
{% block title_content %}选择文件{% endblock %}
{% block script_content %}

    <script type="text/javascript">
        $(function () {
            $("#btn").on('click', function () {
                console.log("come in ")
                const intelval = setInterval(function () {
                    //执行ajax
                    $.ajax({
                        url: "{% url 'trafficflowprediction:upload' %}",
                        data: {
                            getProgressNum: 1,
                        },
                        dataType: "text",
                        type: "get",
                        success: function (result) {
                            console.log('上传进度: ' + result + '%');
                            $('.progress-bar').css('width', result + '%');
                            $('.progress-bar').text(result + '%');
                        }
                    })
                }, 1000)


                //创建对象
                var formdata = new FormData();
                //这里FormData是一个jquery对象，用来绑定values对象，
                //也可以用来上传二进制文件，有了他就可以不用form表单来上传文件了

                var file_obj = $('[name=myfile]')[0].files[0];
                var csrf_data = $('[name=csrfmiddlewaretoken]').val();
                formdata.append('file_obj', file_obj);
                formdata.append('csrfmiddlewaretoken', csrf_data);

                $.ajax({
                    url: '{% url "trafficflowprediction:upload" %}',
                    type: 'post',
                    data: formdata,
                    processData: false,    // 不处理数据
                    contentType: false,    // 不设置内容类型
                    success: function (response) {
                        console.log(response);
                        $('.progress-bar').css('width', '100%');
                        $('.progress-bar').text('100%');
                        //清除Internal
                        clearInterval(intelval);
                    }
                })
            })
        })
    </script>
{% endblock %}

{# 选择文件，显示上传进度条，上传成功 #}

{% block data_content %}
    {% csrf_token %}
    <br/><input class="form-control" type="file" name="myfile">
    <br/>
    <button class="btn btn-primary" id="btn">上传</button>
    <br/><span class="form-control">上传进度</span>
    <div class="progress">
        <div class="progress-bar progress-bar-striped" role="progressbar" aria-valuenow="60"
             aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
        </div>
    </div>
{% endblock %}